### Site info:
title: 
tagline: 
author: Gabriel Ochoa
email: 
description: "" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost/" # the base hostname & protocol for your site


### Personal info and site tools info:
twitter_username: electriclogic
github_username:  gabeochoa
disqus_shortname: freshman21
favicon:     "/images/favicon.ico"
aboutme: Howdy All. # these are shown on aboutme-sidebar.
aboutme_photo: https://i.imgur.com/Mdc4szJl.jpg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en),  Chinese (cn), working on korean. 

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Resent_Posts: "Resent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    cn:
      Aboutme: "关于我"
      Archives: "存档"
      Blogroll: "良师益友"        
      Categories: "分类目录"    
      Copyright_Notice: "版权声明"
      Resent_Posts: "近期文章"
      Tags: "标签" 
      Previous: "前一页"
      Next: "后一页"
      PostedInCategories: "目录:"   
      Taggedwith: "| 标签:"
      PostDate: "| 发表时间: "
    ko:
      Aboutme: "저눈"
      Archives: ""
      Blogroll: ""        
      Categories: ""    
      Copyright_Notice: ""
      Resent_Posts: ""
      Tags: "" 
      Previous: ""
      Next: ""
      PostedInCategories: ":"   
      Taggedwith: "| :"
      PostDate: "| : "


### your Blogroll info, only name can shown on the page.

Blogroll:
    - name: GabeOchoa
      href: http://gabeochoa.me
      title: Life
    - name: author's website
      href: http://ochoag.com/
      title: Gabriel Ochoa's website


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
